# Generated by Django 5.2.3 on 2025-06-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserInfo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic_name", models.CharField(max_length=264, unique=True)),
            ],
        ),
    ]
