# Generated by Django 5.2.3 on 2025-06-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0002_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
