# Generated by Django 5.2.3 on 2025-06-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserInfo", "0003_delete_topic"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Users",
        ),
    ]
