# Generated by Django 5.2.3 on 2025-06-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserInfo", "0004_rename_user_users"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="User",
        ),
    ]
