# Generated by Django 5.2.3 on 2025-06-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppThree', '0002_user_rename_email_userprofile_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
