# Generated by Django 5.2.3 on 2025-07-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0002_remove_userprofileinfo_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofileinfo",
            name="portfolio_site",
        ),
        migrations.AddField(
            model_name="userprofileinfo",
            name="bio",
            field=models.TextField(blank=True),
        ),
    ]
