# Generated by Django 5.2.3 on 2025-07-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0003_remove_userprofileinfo_portfolio_site_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofileinfo",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
