# Generated by Django 5.2.3 on 2025-07-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0004_alter_userprofileinfo_profile_pic"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfileInfo",
        ),
    ]
